spring.application.name=api

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/retrobolsa_db
spring.datasource.username=retrobolsa_user
spring.datasource.password=retrobolsa_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Configzinha do JWT

jwt.secret=b3da5df6b77d2de9304852e72a078d2566794cdb2ebf93e4eb02c6f2eb25b086
jwt.expiration=86400000
